name = "OnePhase"
uuid = "efcca8c6-bf61-49b0-9196-0b50a45fb564"
authors = ["fah33", "ohinder"]
version = "0.2.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsJuMP = "792afdf1-32c1-5681-94e0-d7bf7a5df49e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
advanced_timer = "4dc304fd-12b9-49bd-b6c0-9406f1c5c81b"

[compat]
julia = "1.6"
NLPModels = "0.15.0"
JuMP = "0.21.8"
NLPModelsJuMP = "0.8.2"
MathOptInterface = "0.9.22"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DelimitedFiles"]
